In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df=pd.read_csv("Algerian_forest_cleanded_dataset.csv")
df

     Temperature  RH  Rain  FFMC   DMC    DC  ISI  FWI  Classes
0             29  57   0.0  65.7   3.4   7.6  1.3  0.5        0
1             29  61   1.3  64.4   4.1   7.6  1.0  0.4        0
2             26  82  13.1  47.1   2.5   7.1  0.3  0.1        0
3             25  89   2.5  28.6   1.3   6.9  0.0  0.0        0
4             27  77   0.0  64.8   3.0  14.2  1.2  0.5        0
..           ...  ..   ...   ...   ...   ...  ...  ...      ...
238           30  65   0.0  85.4  16.0  44.5  4.5  6.5        1
239           28  87   4.4  41.1   6.5   8.0  0.1  0.0        0
240           27  87   0.5  45.9   3.5   7.9  0.4  0.2        0
241           24  54   0.1  79.7   4.3  15.2  1.7  0.7        0
242           24  64   0.2  67.3   3.8  16.5  1.2  0.5        0

[243 rows x 9 columns]

In [23]:
df=df.drop("FWI",axis=1)
corr=df.corr()
corr

,Temperature,RH,Rain,FFMC,DMC,DC,ISI,Classes
Temperature,1.000000,-0.651400,-0.326492,0.676568,0.485687,0.376284,0.603871,0.516015
RH,-0.651400,1.000000,0.222356,-0.644873,-0.408519,-0.226941,-0.686667,-0.432161
Rain,-0.326492,0.222356,1.000000,-0.543906,-0.288773,-0.298023,-0.347484,-0.379097
FFMC,0.676568,-0.644873,-0.543906,1.000000,0.603608,0.507397,0.740007,0.769492
DMC,0.485687,-0.408519,-0.288773,0.603608,1.000000,0.875925,0.680454,0.585658
DC,0.376284,-0.226941,-0.298023,0.507397,0.875925,1.000000,0.508643,0.511123
ISI,0.603871,-0.686667,-0.347484,0.740007,0.680454,0.508643,1.000000,0.735197
Classes,0.516015,-0.432161,-0.379097,0.769492,0.585658,0.511123,0.735197,1.000000

In [24]:
corr = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

In [25]:
corr

,Temperature,RH,Rain,FFMC,DMC,DC,ISI,Classes
Temperature,NaN,-0.6514,-0.326492,0.676568,0.485687,0.376284,0.603871,0.516015
RH,NaN,NaN,0.222356,-0.644873,-0.408519,-0.226941,-0.686667,-0.432161
Rain,NaN,NaN,NaN,-0.543906,-0.288773,-0.298023,-0.347484,-0.379097
FFMC,NaN,NaN,NaN,NaN,0.603608,0.507397,0.740007,0.769492
DMC,NaN,NaN,NaN,NaN,NaN,0.875925,0.680454,0.585658
DC,NaN,NaN,NaN,NaN,NaN,NaN,0.508643,0.511123
ISI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.735197
Classes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
to_drop=[col for col in corr.columns if any(corr[col]>0.80)]

In [33]:
to_drop

['DC']